FROM container-registry.oracle.com/graalvm/native-image:21-ol8 AS builder

RUN microdnf install findutils
# Set the working directory to /home/app
WORKDIR /build

# Copy the source code into the image for building
COPY . /build

# Build
RUN ./gradlew nativeCompile

# The deployment Image
FROM container-registry.oracle.com/os/oraclelinux:8-slim

EXPOSE 8080

# Copy the native executable into the containers
COPY --from=builder /build/build/native/nativeCompile/spring_boot_test app
ENTRYPOINT ["/app"]