{
 "title": "Work Done",
 "description": "message consumed by technology",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_system_seconds_total{container_label_com_docker_compose_service=\"go_kafka_consumer\"}[1m])",
     "legendFormat": "GO"
    },
    {
     "expr": "rate(container_cpu_system_seconds_total{container_label_com_docker_compose_service=\"java_se_kafka_consumer\"}[1m])",
     "legendFormat": "JAVA_NATIVE"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service=\"go_kafka_consumer\"}/1000000",
     "legendFormat": "GO"
    },
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service=\"java_se_kafka_consumer\"}/1000000",
     "legendFormat": "JAVA_SE_NATIVE"
    }
   ]
  },
  {
   "title": "Message Consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "message_consumed_counter_java_total",
     "legendFormat": "JAVA_SE_NATIVE"
    },
    { "expr": "message_consumed_counter_go", "legendFormat": "GO" },
    { "expr": "message_produced_counter_total", "legendFormat": "PRODUCED" }
   ]
  }
 ]
}